"""initial

Revision ID: 8c8816c4cded
Revises:
Create Date: 2026-05-20 14:44:39.505636

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8c8816c4cded"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("corporate_number", sa.String(length=13), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("official_url", sa.String(length=2048), nullable=False),
        sa.Column("hq_prefecture", sa.String(length=10), nullable=False),
        sa.Column("hq_address", sa.String(length=500), nullable=True),
        sa.Column("estimated_category", sa.String(length=50), nullable=False),
        sa.Column("tech_stack", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("hiring_roles", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("llm_confidence", sa.String(length=10), nullable=False),
        sa.Column("release_flag", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "corporate_number IS NULL OR length(corporate_number) = 13",
            name="ck_company_corporate_number_length",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("corporate_number"),
        sa.UniqueConstraint("official_url"),
    )
    op.create_table(
        "processing_log",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("phase", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("target_company", sa.String(length=255), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("raw_response", sa.Text(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "company_field",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("field_name", sa.String(length=100), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("raw_value", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["company_id"], ["company.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("company_field")
    op.drop_table("processing_log")
    op.drop_table("company")
    # ### end Alembic commands ###
