"""add_company_info_fields

Revision ID: ad2fa147311f
Revises: ba147b093133
Create Date: 2026-05-21 10:18:50.344350

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ad2fa147311f"
down_revision: Union[str, None] = "ba147b093133"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("company_metrics", sa.Column("employee_count", sa.Integer(), nullable=True))
    op.add_column("company_metrics", sa.Column("average_age", sa.Float(), nullable=True))
    op.add_column("company_metrics", sa.Column("capital_10k_yen", sa.Integer(), nullable=True))
    op.add_column("company_metrics", sa.Column("is_listed", sa.Boolean(), nullable=True))
    op.add_column("company_metrics", sa.Column("founded_year", sa.Integer(), nullable=True))
    op.add_column("company_metrics", sa.Column("ow_score_treatment", sa.Float(), nullable=True))
    op.add_column("company_metrics", sa.Column("ow_score_morale", sa.Float(), nullable=True))
    op.add_column("company_metrics", sa.Column("ow_score_openness", sa.Float(), nullable=True))
    op.add_column("company_metrics", sa.Column("ow_score_growth", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("company_metrics", "ow_score_growth")
    op.drop_column("company_metrics", "ow_score_openness")
    op.drop_column("company_metrics", "ow_score_morale")
    op.drop_column("company_metrics", "ow_score_treatment")
    op.drop_column("company_metrics", "founded_year")
    op.drop_column("company_metrics", "is_listed")
    op.drop_column("company_metrics", "capital_10k_yen")
    op.drop_column("company_metrics", "average_age")
    op.drop_column("company_metrics", "employee_count")
    # ### end Alembic commands ###
