"""add_company_metrics

Revision ID: ba147b093133
Revises: 8c8816c4cded
Create Date: 2026-05-20 16:10:28.499964

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ba147b093133"
down_revision: str | None = "8c8816c4cded"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company_metrics",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("openwork_score", sa.Float(), nullable=True),
        sa.Column("openwork_review_count", sa.Integer(), nullable=True),
        sa.Column("avg_overtime_hours", sa.Float(), nullable=True),
        sa.Column("paid_leave_rate", sa.Float(), nullable=True),
        sa.Column("avg_annual_salary", sa.Integer(), nullable=True),
        sa.Column("new_grad_salary_min", sa.Integer(), nullable=True),
        sa.Column("new_grad_salary_max", sa.Integer(), nullable=True),
        sa.Column("remote_work_policy", sa.String(length=20), nullable=True),
        sa.Column("new_grad_headcount", sa.Integer(), nullable=True),
        sa.Column("has_current_openings", sa.Boolean(), nullable=True),
        sa.Column("openwork_url", sa.String(length=2048), nullable=True),
        sa.Column("green_url", sa.String(length=2048), nullable=True),
        sa.Column(
            "scraped_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["company_id"], ["company.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("company_metrics")
    # ### end Alembic commands ###
